### ISSUE TITLE
压缩后的新目录不存在，对应的压缩后视频也不存在，没压缩成功？

### ISSUE THREAD

**Issue by qianfeifeio** [ITxiaoguang/VideoCompress#1]
选择视频后，虽然提示压缩成功，但是 压缩后的新目录根本不存在，对应的压缩后视频也不存在，没压缩成功？

**Comment by ITxiaoguang** [comment]
是的，稍后帮您解决哈

**Comment by ITxiaoguang** [comment]
bug已修改好啦~  请使用 1.2.0版本

1.2.0版本：
修改bug：添加aspectjrt-1.7.3.jar包
新增：支持自定义输出文件路径
